1 task Hacker2999
studokim/practices pull request #1
Opened 2023-11-10 12:21 UTC by Hacker2999

2023-11-14 07:56 UTC, studokim requested changes

2023-11-14 07:56 UTC, studokim commented on solution/work1/.kdev4/work1.kdev4
> +[Buildset]
Не стоит добавлять в репозиторий конфиги, специфические для своей машины.

2023-11-14 07:56 UTC, studokim commented on solution/work1/build/.cmake/api/v1/query/client-kdevelop/query.json
> +{"requests": [{"kind": "codemodel", "version": 2}, {"kind": "cmakeFiles", "version": 1}]}
Не стоит добавлять в репозиторий временные файлы, создающиеся при сборке.

2023-11-14 07:56 UTC, studokim commented on solution/work1/main.cpp
> +        if (reader.ParseError() < 0){
`.ParseError()` иногда возвращает положительное число. Как этот случай будет обработан?

2023-11-14 07:56 UTC, studokim commented on solution/work1/main.cpp
> +#include "inih-master/ini.c"
Не следует инклюдить `.c` и `.cpp` файлы, поскольку `#include` обрабатывается препроцессором. Получается то же самое, как если бы вы прямо скопировали весь код в `main.cpp`

Корректный путь — инклюдить только заголовочный файл, а подключение исполняемого кода доверить линковщику.

**Задача**: настроить проект так, чтобы обойтись единственной строкой `#include "inih-master/cpp/INIReader.h"`, как и в [примере](https://github.com/benhoyt/inih#c-example).

2023-11-14 07:56 UTC, studokim commented on solution/work1/main.cpp
> +            redt= reader.GetInteger("timings","red",-1);
Почему значение по умолчанию = -1?

2023-11-14 07:56 UTC, studokim commented on solution/work1/main.cpp
> +    }
Что будет, если опечататься и вызвать `displayColor("ree")`?

2023-11-14 07:56 UTC, studokim commented on solution/work1/main.cpp
> +    }
Можно ли сделать `displayColor()` private?

2023-11-14 07:56 UTC, studokim commented on solution/work1/main.cpp
> +    void view() {
Хотелось бы видеть вертикальный светофор, а один квадратик — не наглядно: ![image](https://github.com/studokim/practices/assets/48129887/fa184708-26b2-4c9c-83a2-5abd6937e40d)

2023-11-14 07:56 UTC, studokim commented on solution/work1/main.cpp
> +    void view() {
Алгоритм сейчас косячный: 

1. красный
2. жёлтый
3. зелёный
4. мигающий зелёный
5. красный

Верный алгоритм:

1. красный
2. красный + жёлтый
3. зелёный
4. мигающий зелёный
5. жёлтый
6. красный

2023-11-14 07:56 UTC, studokim commented on solution/work1/main.cpp
> +    traffic_light aboba;
aboba?

2023-11-14 07:56 UTC, studokim commented on solution/work1/main.cpp
> +    void displayColor(const std::string& color) {
Давайте использовать в проекте единый стиль: snake_case или camelCase?

2023-11-14 07:56 UTC, studokim commented on solution/work1/main.cpp
> +    void displayColor(const std::string& color) {
```cpp
void f() {
...

void h()
{
...
```

Отступы и скобки тоже должны быть единообразными. Проще всего настроить автоформаттер.

2023-11-14 08:02 UTC, studokim commented on solution/work1/main.cpp
> +#include "inih-master/ini.c"
И знаете, давайте копирование чужой библиотеки `inih-master` сохранять отдельным коммитом. А ещё лучше научиться использовать `git submodule`.

2023-11-15 10:42 UTC, Hacker2999 commented on solution/work1/main.cpp
> +    void displayColor(const std::string& color) {
Внёс изменения в проект

2023-11-15 11:02 UTC, studokim commented on solution/work1/main.cpp
> +    void displayColor(const std::string& color) {
На каждый коммент можно нажать «resolve»?

2023-11-15 11:22 UTC, Hacker2999 commented on solution/work1/main.cpp
> +    void displayColor(const std::string& color) {
да

2023-11-15 11:47 UTC, studokim commented on solution/work1/main.cpp
> +    void displayColor(const std::string& color) {
Так жмите смелее :)
Переформулировал сообщение в телеге*

2023-11-15 12:16 UTC, studokim requested changes

2023-11-15 12:16 UTC, studokim commented on solution/work1/build/work1
За крайне редким исключением, бинарники тоже не надо коммитить. Предлагаю всю директорию `build` добавить в `.gitignore`.

2023-11-15 12:16 UTC, studokim commented on solution/work1/main.cpp
> +        else
Можно ли сделать эту проверку в compile-time?

2023-11-15 12:16 UTC, studokim commented on solution/work1/main.cpp
> +        if (reader.ParseError() < 0)
Должен ли пользователь знать, что содержимое `timings.ini` некорректное и настройки не были применены? Или достаточно лишь сообщить, когда файл вообще не найден?

2023-11-15 12:16 UTC, studokim commented on solution/work1/main.cpp
> +    return 0;
Когда будет вызван return?

2023-11-15 12:19 UTC, Hacker2999 commented on solution/work1/main.cpp
> +    return 0;
никогда, в view() находится бесконечный цикл

2023-11-15 12:23 UTC, studokim commented on solution/work1/main.cpp
> +        if (reader.ParseError() < 0)
Что делать, если пользователь создал такой файл?

```yml
[timings]
red=-1
green=4

```

2023-11-15 12:33 UTC, Hacker2999 commented on solution/work1/main.cpp
> +        else
скорее всего да, напишу и сделаю commit

2023-11-20 13:28 UTC, studokim commented
Принято, отличная работа! :)

2023-11-20 13:28 UTC, closed without merging