Светофор
studokim/practices pull request #2
Opened 2023-11-10 12:32 UTC by Rshfr

2023-11-14 08:36 UTC, studokim requested changes

2023-11-14 08:36 UTC, studokim commented on solution/project_1/.kdev4/project_1.kdev4
> +[Buildset]
Не стоит добавлять в репозиторий конфиги, специфические для своей машины.

2023-11-14 08:36 UTC, studokim commented on solution/project_1/build/CMakeCache.txt
> +# This is the CMakeCache file.
Не стоит добавлять в репозиторий временные файлы, создающиеся при сборке.

2023-11-14 08:36 UTC, studokim commented on solution/project_1/inih-master/tests/user_error.ini
> +[section]
Если вы не привязываетесь к конкретной версии библиотеки (релизу), а используете свежий код прямо из репозитория, то следует подключить её командой `git submodule`, а не добавлять сотню чужих файлов в том же коммите, в каком вы сохраняете свой код.

2023-11-14 08:36 UTC, studokim commented on solution/project_1/main.cpp
> +            std::this_thread::sleep_for(std::chrono::seconds(r_time));
Алгоритм неверный, программа не выполняет функции светофора:

1. мигающий зелёный
2. жёлтый
3. красный
4. пустота?

2023-11-14 08:36 UTC, studokim commented on solution/project_1/main.cpp
> +    return 0;
Когда будет вызван `return`?

2023-11-14 08:36 UTC, studokim commented on solution/project_1/main.cpp
> +    void color_time(int g_time, int y_time, int r_time)
Название функции не отражает сути её существования. Подумайте. Если нельзя придумать хорошего названия, может быть функция не нужна вовсе?

Если решите сохранить её, расскажите, почему она `public`.

2023-11-14 08:36 UTC, studokim commented on solution/project_1/main.cpp
> +            std::cout << "Error\n";
Пользователь (я) компилирует программу, запускает её и видит `Error`. Как ему понять, что пошло не так, не глядя в исходники?

2023-11-14 08:36 UTC, studokim commented on solution/project_1/main.cpp
> +#include "./inih-master/ini.h"
Не следует инклюдить `.c` и `.cpp` файлы, поскольку `#include` обрабатывается препроцессором. Получается то же самое, как если бы вы прямо скопировали весь код в `main.cpp`.

Корректный путь — инклюдить только заголовочный файл, а подключение исполняемого кода доверить линковщику.

Задача: настроить проект так, чтобы обойтись единственной строкой `#include "inih-master/cpp/INIReader.h"`, как и в [примере](https://github.com/benhoyt/inih#c-example).

2023-11-14 08:36 UTC, studokim commented on solution/project_1/path.ini
> +[color]
Глядя на название файла `path` и название секции `color`, невозможно предположить, что эти числа означают тайминги в секундах.

2023-11-14 08:36 UTC, studokim commented on solution/project_1/main.cpp
> +    traffic_light A("../path.ini");
`A`?

Рекомендуется для названий классов использовать PascalCase, т.е. начинать их с большой буквы, потому что:

- переменных много, класс один
- если переменная типа `TrafficLight` одна, мы сможем назвать её `trafficLight`, просто сменив регистр и никого не запутав

2023-11-14 08:36 UTC, studokim commented on solution/project_1/main.cpp
> +                std::cout << "\033[42m    \n    \033[0m" << std::endl;
Читая `work()` и эту строчку в частности, невозможно понять, что она рисует цветные квадратики aka лампочки.

2023-11-14 08:36 UTC, studokim commented on solution/project_1/main.cpp
> +            std::this_thread::sleep_for(std::chrono::seconds(r_time));
Хотелось бы видеть вертикальный светофор, а один квадратик — не наглядно: ![image](https://github.com/studokim/practices/assets/48129887/fa184708-26b2-4c9c-83a2-5abd6937e40d)

2023-11-14 08:37 UTC, studokim commented on solution/project_1/main.cpp
> +            std::cout << "Error\n";
`.ParseError()` иногда возвращает положительное число. Как этот случай будет обработан?

2023-11-15 12:34 UTC, studokim requested changes

2023-11-15 12:34 UTC, studokim commented on solution/project_1/build/project_1
За крайне редким исключением, бинарники тоже не надо коммитить. Предлагаю всю директорию `build` добавить в `.gitignore`.

2023-11-15 12:34 UTC, studokim commented on solution/project_1/main.cpp
>          while (true)
По-прежнему алгоритм неверный: у меня зелёный отрисовывается в не той строке и мигает розовым.

2023-11-15 12:34 UTC, studokim commented on solution/project_1/main.cpp
> +class TrafficLights
Этот класс обслуживает один светофор, а не светофор**ы**.

2023-11-15 12:34 UTC, studokim commented on solution/project_1/main.cpp
>      return 0;
И всё-таки, когда будет вызван return?

2023-11-15 12:34 UTC, studokim commented on solution/project_1/main.cpp
> +        r_time = reader.GetInteger("timings", "red", 2);
Должен ли пользователь знать, что конфиг неверный и был проигнорирован?

Как будет обработан файл следующего вида?

```yml
[timings]
red=-1
green=4

```

2023-11-15 12:34 UTC, studokim commented on solution/project_1/main.cpp
> +    void cout_light(const std::string& color)
Что если опечататься и вызвать `cout_light("ree")`?

2023-11-20 06:52 UTC, studokim requested changes
Вообще-то хорошо, но давайте добъём до идеала. Ответьте в этот раз текстом в комментах

2023-11-20 06:52 UTC, studokim commented on solution/project_1/main.cpp
> +            std::cout << "Invalid timing value\nStandard values will be applied (2 seconds)\n";
Одобряю

2023-11-20 06:52 UTC, studokim commented on solution/project_1/main.cpp
> +        std::cout << "\033[42m   \033[0m\r" << std::flush;
Не понял, почему выше `endl`, а здесь `flush`

2023-11-20 06:52 UTC, studokim commented on solution/project_1/main.cpp
> +            std::cout << "Unknown color: " << color << std::flush;
Можно ли выполнить эту проверку во время компиляции?

2023-11-20 06:52 UTC, studokim commented on solution/project_1/main.cpp
> +            std::cout << "Invalid timing value\nStandard values will be applied (2 seconds)\n";
Только, кажется, здесь не хватает как раз `flush`. Чем отличается простой `\n` от `endl`?

2023-11-20 10:04 UTC, Rshfr commented on solution/project_1/main.cpp
> +        std::cout << "\033[42m   \033[0m\r" << std::flush;
Зеленый - последний цвет и переносить каретку на новую строку нам не надо

2023-11-20 10:09 UTC, Rshfr commented on solution/project_1/main.cpp
> +        std::cout << "\033[42m   \033[0m\r" << std::flush;
В конце мы возвращаем каретку в начало строки, чтобы потом на месте зеленого цвета вывести "пустой"

2023-11-20 10:24 UTC, Rshfr commented on solution/project_1/main.cpp
> +            std::cout << "Invalid timing value\nStandard values will be applied (2 seconds)\n";
\n осуществляет переход на новую строку, а endl плюс к этому очищает буфер

2023-11-20 14:14 UTC, studokim commented on solution/project_1/main.cpp
> +            std::cout << "Invalid timing value\nStandard values will be applied (2 seconds)\n";
Что это значит для нас? Зачем очищать буфер? Когда не нужно его очищать?

2023-11-20 14:27 UTC, Rshfr commented on solution/project_1/main.cpp
> +            std::cout << "Invalid timing value\nStandard values will be applied (2 seconds)\n";
Согласен, тут правильнее было бы написать endl, чтобы сообщение сразу вывелось и не заполняло буфер

2023-11-20 14:29 UTC, Rshfr commented on solution/project_1/main.cpp
> +            std::cout << "Unknown color: " << color << std::flush;
Можно цвета прописать в enum и именно их передавать как параметр, а не строку с цветом

2023-11-20 14:35 UTC, studokim commented on solution/project_1/main.cpp
> +            std::cout << "Invalid timing value\nStandard values will be applied (2 seconds)\n";
Всё-таки ответьте на прямой вопрос)

2023-11-20 14:36 UTC, studokim commented on solution/project_1/main.cpp
> +            std::cout << "Unknown color: " << color << std::flush;
Какой `enum` вы бы стали здесь использовать: `enum class` или `enum`? Почему,

2023-11-20 14:36 UTC, studokim commented on solution/project_1/main.cpp
> +        std::cout << "\033[42m   \033[0m\r" << std::flush;
Ок

2023-11-20 14:48 UTC, Rshfr commented on solution/project_1/main.cpp
> +            std::cout << "Invalid timing value\nStandard values will be applied (2 seconds)\n";
cout записывает в буфер, а flush заставляет его очистить, т е вывести данные из буфера

2023-11-20 14:56 UTC, studokim commented on solution/project_1/main.cpp
> +            std::cout << "Invalid timing value\nStandard values will be applied (2 seconds)\n";
Ок

2023-11-20 15:19 UTC, Rshfr commented on solution/project_1/main.cpp
> +            std::cout << "Unknown color: " << color << std::flush;
enum class
enum неявно преобразуется в int. а enum class создает свой собственный тип 
Элементы enum class лежат в собственной области видимости, что помогает избегать конфликта имен

2023-11-21 06:54 UTC, studokim commented on solution/project_1/main.cpp
> +            std::cout << "Unknown color: " << color << std::flush;
Принято!

2023-11-21 06:55 UTC, studokim approved these changes

2023-11-21 06:55 UTC, studokim commented
Задача принята

2023-11-21 06:55 UTC, closed without merging