project 1
studokim/practices pull request #3
Opened 2023-11-11 18:22 UTC by TheIgor23

2023-11-14 09:03 UTC, studokim requested changes

2023-11-14 09:03 UTC, studokim commented on solution/project_1/build/CMakeCache.txt
> +# This is the CMakeCache file.
Не стоит добавлять в репозиторий временные файлы, создающиеся при сборке.

2023-11-14 09:03 UTC, studokim commented on solution/project_1/main.cpp
> +#include "inih/cpp/INIReader.h"
Не следует инклюдить `.c` и `.cpp` файлы, поскольку `#include` обрабатывается препроцессором. Получается то же самое, как если бы вы прямо скопировали весь код в `main.cpp`.

Корректный путь — инклюдить только заголовочный файл, а подключение исполняемого кода доверить линковщику.

**Задача**: настроить проект так, чтобы обойтись единственной строкой `#include "inih/cpp/INIReader.h"`, как и в [примере](https://github.com/benhoyt/inih#c-example).

2023-11-14 09:03 UTC, studokim commented on solution/project_1/main.cpp
> +};
Хотелось бы видеть вертикальный светофор, а один квадратик — не наглядно: ![image](https://github.com/studokim/practices/assets/48129887/fa184708-26b2-4c9c-83a2-5abd6937e40d)

2023-11-14 09:03 UTC, studokim commented on solution/project_1/main.cpp
> +	TrafficLights(vector<Signal> s)
Зачем `vector`, если у нас известное и постоянное число сигналов?

2023-11-14 09:03 UTC, studokim commented on solution/project_1/main.cpp
> +class TrafficLights
Класс обслуживает единственный светофор, а не светофор**ы**.

2023-11-14 09:03 UTC, studokim commented on solution/project_1/main.cpp
> +			for(int i = 0; i<signals.size(); i++)
Почему здесь счётчик `int`, а ниже `size_t`?

2023-11-14 09:03 UTC, studokim commented on solution/project_1/main.cpp
> +	int redt = reader.GetInteger("timings", "red", 4),
Как `long`, возвращаемый функцией, конвертируется в `int`?

2023-11-14 09:03 UTC, studokim commented on solution/project_1/main.cpp
> +};
Алгоритм сейчас косячный: 

1. красный
2. жёлтый
3. зелёный
4. мигающий зелёный
5. красный

Верный алгоритм:

1. красный
2. красный + жёлтый
3. зелёный
4. мигающий зелёный
5. жёлтый
6. красный

2023-11-14 09:03 UTC, studokim commented on solution/project_1/main.cpp
> +	return 0;
Когда будет вызван `return`?

2023-11-14 09:17 UTC, TheIgor23 commented on solution/project_1/main.cpp
> +	return 0;
Никогда. В методе Start используется бесконечный цикл

2023-11-14 09:19 UTC, TheIgor23 commented on solution/project_1/main.cpp
> +	int redt = reader.GetInteger("timings", "red", 4),
Неявным преобразованием.
Лучше использовать явное преобразование или просто изменить тип на long?

2023-11-14 09:36 UTC, studokim commented on solution/project_1/main.cpp
> +	int redt = reader.GetInteger("timings", "red", 4),
Есть риск [undefined behaviour](https://en.cppreference.com/w/cpp/language/operator_arithmetic#Overflows).

2023-11-15 13:00 UTC, studokim requested changes

2023-11-15 13:00 UTC, studokim commented on solution/project_1/main.cpp
>  	trL.Start();
Светофор выключается после одной итерации.

2023-11-15 13:00 UTC, studokim commented on solution/project_1/main.cpp
> +		signals = new Signal[SIGNAL_SIZE]
Почему мы не можем обойтись памятью на стеке?

2023-11-15 13:00 UTC, studokim commented on solution/project_1/main.cpp
> +	this_thread::sleep_for(chrono::seconds(timeSleepSecond));
Почему здесь `timeSleepSecond`, а ниже `600`?

2023-11-15 13:00 UTC, studokim commented on solution/project_1/main.cpp
> +	for (size_t i = 0; i < 3; i++)
Почему здесь `size_t`, а ниже `int`?

2023-11-15 13:00 UTC, studokim commented on solution/project_1/main.cpp
> +	const int SIGNAL_SIZE = 5;
Константа меняется независимо от содержимого массива. Как поведёт себя `Start()`, если, например, удалить 45-ю строчку `{"\x1B[41m   \x1B[0m\n", redTime, displayColor},`?

2023-11-15 13:03 UTC, studokim commented on solution/project_1/main.cpp
>  	trL.Start();
Если строчка `return` никогда не вызывается, она ведь нам не нужна — мёртвый код.

2023-11-15 13:32 UTC, TheIgor23 commented on solution/project_1/main.cpp
> +	const int SIGNAL_SIZE = 5;
На последней итерации цикла будет вызвана ошибка, тк элементов в массиве меньше

2023-11-15 13:37 UTC, TheIgor23 commented on solution/project_1/main.cpp
> +	this_thread::sleep_for(chrono::seconds(timeSleepSecond));
Для создания эффекта мерцания цвета. Если мы ниже используем timeSleepSecond, то будет слишком большой промежуток между мерцанием

2023-11-15 13:39 UTC, TheIgor23 commented on solution/project_1/main.cpp
> +		signals = new Signal[SIGNAL_SIZE]
У меня возникли проблемы с инициализацией статического массива в конструкторе. 
Можете сказать, как корректнее это реализовать ?

2023-11-15 13:51 UTC, TheIgor23 commented on solution/project_1/main.cpp
> +	this_thread::sleep_for(chrono::seconds(timeSleepSecond));
Хотелось бы узнать, насколько корректна была моя реализация через указатели на функцию ? Есть ли вообще смысл их использовать тут ?

2023-11-16 07:48 UTC, studokim commented on solution/project_1/main.cpp
> +	this_thread::sleep_for(chrono::seconds(timeSleepSecond));
Я лично считаю, что это overkill, хотя и имеющий право на жизнь. Основная претензия к вашей реализации в том, что она создаёт дополнительную сложность: нужно без помощи компилятора уследить за разными кусками класса, чтобы она не упала с segfault — причём ещё и не сразу после запуска, а к концу итерации (см. [коммент ниже](https://github.com/studokim/practices/pull/3#discussion_r1394204494)). Если получится защититься от этого, то будем считать, что всё ОК.

2023-11-16 08:01 UTC, studokim commented on solution/project_1/main.cpp
> +	this_thread::sleep_for(chrono::seconds(timeSleepSecond));
Подсказка: попробуйте вместо C-style array использовать `std::array`. Почему — см. книжку The C++ Programming Language, §12.2.2. Чем это лучше `std::vector`, напишите здесь сами.

2023-11-16 08:02 UTC, studokim commented on solution/project_1/main.cpp
> +	const int SIGNAL_SIZE = 5;
Подсказка: попробуйте вместо C-style array использовать `std::array`. Почему — см. книжку The C++ Programming Language, §12.2.2. Чем это лучше `std::vector`, напишите здесь сами.

2023-11-16 08:03 UTC, studokim commented on solution/project_1/main.cpp
> +		signals = new Signal[SIGNAL_SIZE]
См. [коммент ниже](https://github.com/studokim/practices/pull/3#discussion_r1395292055)

2023-11-16 08:05 UTC, studokim commented on solution/project_1/main.cpp
> +	this_thread::sleep_for(chrono::seconds(timeSleepSecond));
Что касается `timeSleepSecond` vs `600`, мб. стоит разделить `displayColor()` и `animateColor()`, чтобы было нагляднее

2023-11-16 11:38 UTC, TheIgor23 commented on solution/project_1/main.cpp
> +	const int SIGNAL_SIZE = 5;
Как я понял, std::array при передаче в качестве аргумента не превращается в указатель и предназначен для работы с фиксированным размером.
Тогда как избежать ошибки, если количество элементов в массиве меньше заданного размера?

2023-11-16 19:15 UTC, studokim commented on solution/project_1/main.cpp
> +	const int SIGNAL_SIZE = 5;
А это надо придумать самостоятельно.

Можете не привязываться к `std::array`, это лишь один из вариантов.

2023-11-22 13:58 UTC, studokim reviewed
Задача почти принята. Можете ответить текстом.

2023-11-22 13:58 UTC, studokim commented on solution/project_1/main.cpp
> +	array<Signal, 4> signals;
Всё-таки следует сделать явный `#include <array>`

2023-11-22 13:58 UTC, studokim commented on solution/project_1/main.cpp
>  	INIReader reader("../timings.ini");
Что если пользователь создал `timings.ini` со следующим содержимым?

```yml
[timings]
red=1
green=-4
```

2023-11-22 13:58 UTC, studokim commented on solution/project_1/main.cpp
> +		signals =
Класс. Теперь если `signals` перенести из тела конструктора в список инициализации, как вы сделали выше, то при числе элементов, не равном четырём, код даже не скомпилируется. А это как раз то, что нам надо.

Только нужно удалить default конструктор в Signal. Ответьте, зачем?

2023-11-22 14:38 UTC, TheIgor23 commented on solution/project_1/main.cpp
>  	INIReader reader("../timings.ini");
Будет использовано значение, которое мы передаем третьим аргументом в метод GetInteger.
Следует явно оповестить об этом?

2023-11-22 14:51 UTC, TheIgor23 commented on solution/project_1/main.cpp
> +		signals =
Потому что он будет вызван для элементов, которые мы не инициализировали. Программа не выдаст ошибку, но будет работать некорректно

2023-11-22 14:53 UTC, TheIgor23 commented on solution/project_1/main.cpp
> +	array<Signal, 4> signals;
Можно узнать зачем ?

2023-11-23 08:14 UTC, studokim commented on solution/project_1/main.cpp
> +	array<Signal, 4> signals;
Сейчас он у вас подключается неявно. Кажется, `"INIReader.h"` использует `<map>`, который использует `<bits/stl_map.h>`, который использует `<tuple>`, в котором (в качестве костыля) объявлены заголовки `<array>`. Таким образом, вы зависите не только от интерфейса, который предоставляет библиотека, но и от её внутренней реализации, которая может измениться.

Второй момент, чисто утилитарный: если компилятор GCC вы смените на Clang, он такое не съест.

P.S. прошу не жать «Resolve conversation» в том случае, когда задаёте встречный вопрос, т.к. его не видно

2023-11-23 08:21 UTC, studokim commented on solution/project_1/main.cpp
>  	INIReader reader("../timings.ini");
Да. Пользователь *ожидает*, что его конфиг применился, если не сказано обратное

2023-11-23 08:22 UTC, TheIgor23 commented on solution/project_1/main.cpp
> +	array<Signal, 4> signals;
Понятно. Спасибо, что объяснили

2023-11-23 08:22 UTC, studokim commented on solution/project_1/main.cpp
>  	INIReader reader("../timings.ini");
И кроме того, ваша библиотека успешно парсит `-4`, и программа запускается. А что значит «показывать зелёный на протяжении минус четырёх секунд»? Баг.

2023-11-23 08:23 UTC, studokim commented on solution/project_1/main.cpp
> +		signals =
:+1:

2023-11-23 08:59 UTC, studokim commented
Можно переходить к следующей задаче, не забывая полученный опыт :)

2023-11-23 08:59 UTC, closed without merging