Work3
studokim/practices pull request #7
Opened 2023-12-12 12:41 UTC by Hacker2999

2023-12-13 06:50 UTC, studokim commented on solution/LSclient/main.cpp
> +        std::cerr << "Используется: " << argv[0] << " <serverPort> <serverAddress:proxyPort>" << std::endl;
Не понял, почему параметры идут в таком порядке? Кажется очень не логичным, предлагаю

```
Используется: ./LSclient <clientPort> <serverAddress:serverPort>
```

2023-12-13 07:48 UTC, studokim commented on solution/LSclient/main.cpp
> +#include <iostream>
Баги:

- Если сервер отключится, пока ещё не все команды были обработаны, оставшиеся будут выполнены в консоли клиента (см. скриншот). Для `ls` это не страшно, но для `rm` опасно. 
![image](https://github.com/studokim/practices/assets/48129887/de5698c2-6ac3-49ae-96de-b733b70cd30e)
- Нужна валидация команды на клиенте. Он сейчас пропускает любую строку, кроме пустой.
- Нужно сообщение, если сервер не отвечает дольше определённого таймаута. Сейчас неясно, кто завис.

2023-12-18 10:46 UTC, studokim requested changes
На комменты к строчкам 92 и 183 следует ответить. Остальное, если отчёт горит, просто учтите на будущее

2023-12-18 10:46 UTC, studokim commented on solution/LSclient/main.cpp
> +    bool CheckServerStatus()
Если назвать, например, `isServerAlive()`, будет ещё понятнее :)

2023-12-18 10:46 UTC, studokim commented on solution/LSclient/main.cpp
> +            exit(EXIT_FAILURE);
Непонятно, кстати, почему здесь сразу `exit`, а выше просто `return false`

2023-12-18 10:46 UTC, studokim commented on solution/LSclient/main.cpp
> +    bool IsValidCommand(const std::string &command)
private

2023-12-18 10:46 UTC, studokim commented on solution/LSclient/main.cpp
> +    void SendCommand(const std::string &command)
private

2023-12-18 10:46 UTC, studokim commented on solution/LSclient/main.cpp
> +    void ReceiveResponse(char *buffer, int bufferSize)
private

2023-12-18 10:46 UTC, studokim commented on solution/LSclient/main.cpp
> +        if (bind(clientSocket, reinterpret_cast<sockaddr *>(&clientAddr), sizeof(clientAddr)) == -1)
Разве `reinterpret_cast` здесь необходим?

2023-12-18 10:46 UTC, studokim commented on solution/LSclient/main.cpp
> +        int result = select(clientSocket + 1, &readSet, nullptr, nullptr, &timeout);
> WARNING: ...
>       All modern applications should instead use [poll(2)](https://man7.org/linux/man-pages/man2/poll.2.html) or [epoll(7)](https://man7.org/linux/man-pages/man7/epoll.7.html),
>       which do not suffer this limitation.

2023-12-18 10:46 UTC, studokim commented on solution/LSclient/main.cpp
> +const int BufferSize = 1024;
Эта константа — собственность клиента. Заодно избавитесь от sizeof

2023-12-18 10:46 UTC, studokim commented on solution/LSclient/main.cpp
> +            if (!CheckServerStatus())
Кажется, эта функция вам не нужна вовсе? Во-первых, логика `if` дублируется в `ReceiveResponse`. Во-вторых, если вы уже вычитали весь буфер, потеряете и не сможете показать ответ сервера.

2023-12-18 10:46 UTC, studokim commented on solution/LSclient/main.cpp
> +            CheckServerDelay();
Семантика этой функции скорее `WaitForResponse`, верно?

2023-12-18 10:52 UTC, studokim commented
![Screenshot from 2023-12-18 13-00-47](https://github.com/studokim/practices/assets/48129887/b32177ac-9d71-4a41-9c5c-60d24235554c)

Ах да, input по-прежнему выполняется в консоли после завершения программы

2023-12-18 13:12 UTC, Hacker2999 commented on solution/LSclient/main.cpp
> +        if (bind(clientSocket, reinterpret_cast<sockaddr *>(&clientAddr), sizeof(clientAddr)) == -1)
reinterpret_cast используется для приведения типа указателя. Функция bind ожидает указатель на sockaddr, но clientAddr имеет тип sockaddr_in

2023-12-18 15:46 UTC, Hacker2999 commented
С input после завершения программы я так и не смог разобраться, пробовал termios получилось только скрыть ввод от глаз человека, но если не обращая внимания ввести ls и нажать enter то команда выполнится

2023-12-20 07:47 UTC, studokim commented
> С input после завершения программы я так и не смог разобраться, пробовал termios получилось только скрыть ввод от глаз человека, но если не обращая внимания ввести ls и нажать enter то команда выполнится

Скрывать точно не надо. Вы ведь сами понимаете, что тут проблема не в том, что «некрасиво», а в том, что можно стереть что-нибудь важное на машине пользователя.

2023-12-25 12:21 UTC, closed without merging