Proxy
studokim/practices pull request #8
Opened 2023-12-12 19:40 UTC by Rshfr

2023-12-13 08:42 UTC, studokim requested changes

2023-12-13 08:42 UTC, studokim commented on solution/ls-proxy/proxy.cpp
> +                std::cout << "Client disconnected" << std::endl;
Прокси должен ожидать нового подключения клиента

2023-12-13 08:42 UTC, studokim commented on solution/ls-proxy/proxy.cpp
> +    const int proxyPort = std::stoi(strtok(nullptr, ":"));
Как починить?
![image](https://github.com/studokim/practices/assets/48129887/d204069a-6006-4a17-b05d-21803da184eb)

2023-12-13 08:42 UTC, studokim commented on solution/ls-proxy/proxy.cpp
> +                std::cerr << "Error receiving response from server" << std::endl;
Бывают ли ошибки, после которых мы можем восстановить нормальную работу, а не выключаться?

2023-12-18 08:40 UTC, studokim commented on solution/ls-proxy/proxy.cpp
> +    const int proxyPort = std::stoi(strtok(nullptr, ":"));
Ок, один случай пофиксили.

![image](https://github.com/studokim/practices/assets/48129887/9e36e02c-a108-441f-af8f-9318892271b3)

2023-12-18 08:55 UTC, studokim commented on solution/ls-proxy/proxy.cpp
> +                std::cout << "Client disconnected" << std::endl;
Если клиент отключился до того как сервер успел ответить, то новый клиент не может начать работу (т.е. не получает ответов на свои команды). Подсказка: так происходит, потому что старый клиент не вычитал ответ из прокси, следовательно цикл завис

2023-12-18 09:00 UTC, studokim reviewed
Добавил к предыдущим комментам. Будете править или уже пишете отчёт?

2023-12-19 15:58 UTC, Rshfr commented
Уже пишу отчет

2023-12-20 07:17 UTC, closed without merging